name: "Release"
description: "Calculates a new version number based on PR labels. Creates a changelog entry based on content of PR description. Packages the repository up and puts GitHub release."

inputs:
  path:
    description: "Relative path to the changelog file. Defaults to 'CHANGELOG.md'"
    required: false
    default: "CHANGELOG.md"
  user-name:
    description: "UserName to use when committing changelog and other git actions."
    required: true
    default: ""
  user-email:
    description: "Email to use for the user when committing changelog and other git actions."
    required: true
    default: ""
  github-token:
    description: "GitHub token to use within the action when it is performing writing. Defaults to the GITHUB_TOKEN."
    required: false
    default: ${{ github.token }}

outputs:
  should-publish:
    description: "Whether or not a publish should be done"
  version:
    description: " Version number to publish with"

runs:
  using: "node16"
  main: "dist/HandleVersion/index.js"
  post: 'dist/HandleRelease/index.js'
  post-if: 'success()'