name: Build

on:
  push:
    branches:
      - "**"
    paths:
      - "Source/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - run: yarn test
